name: pull-request
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: false
jobs:
  build:
    name: Doo something cool
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment --$PR_URL -body "Welcome to my repa"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}